package main

const PLAYER_SIDE int = 0
const ENEMY_SIDE int = 1

const DEFAULT_HOMEBASE_HEALTH int = 1000
const DEFAULT_BASE_COUNT int = 2
const DEFAULT_BASE_OFFSET_BUFFER float32 = 5.0
const DEFAULT_TICKS_PER_BOUNCER_RESPAWN int = 100
const DEFAULT_TICKS_PER_SHIELD_REGEN int = 15
const DEFAULT_MAX_BOUNCERS int = 6
const DEFAULT_FIRE_DELAY int = 100
